# Generated by argonaut
	
FROM public.ecr.aws/f6j9h7m4/argonautdev/lambda-handler:03e6035 as handler_layer

FROM public.ecr.aws/lambda/nodejs:14

# install dependencies
RUN npm install --production=false

WORKDIR /var/task

ENV ARGONAUT_SERVERLESS_PORT="3000"
ENV ARGONAUT_SERVERLESS_RUN_COMMAND="npm run start"

COPY --from=handler_layer /main /handler

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
ENTRYPOINT [ "/handler" ]